# Terraform Format Starter Workflow Template
# Remove comments before committing

name: "Terraform Format"
on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"

jobs:
  terraform_format_check:
    name: "Terraform Format Check"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test
        run: pwd

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # specify terraform version
          terraform_version: [ $terraform-version ]

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check